Lab1/BookStore/urls.py
from django.urls import path
from .views import index, books_list,book_details,book_delete,book_update,book_add

app_name = 'books'

urlpatterns = [
    path('', index, name='bookStore-index'),
    path('books_list/', books_list, name="books_list"),
    path('book_details/<int:book_id>', book_details, name="book_details"),
    path('book_delete/<int:task_id>', book_delete, name="book_delete"),
    path('book_update/<int:task_id>', book_update, name="book_update"),
    path('book_add/', book_add, name="book_add")
   
]

Lab1/Lab1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BookStore.urls'))
]

Lab1/BookStore/models.py
from django.db import models

# Create your models here.

Lab1/BookStore/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect

# Create your views here.

My_Books = [
    {
        "index": 0,
        "id": 1,
        "name": "Sapiens: A Brief History of Humankind",
        "price": 500,
        "description": "This book explores the history of human beings, from the emergence of Homo sapiens in Africa to the present day. It covers a wide range of topics, including the development of language, the rise of agriculture, the creation of religions, and the growth of empires.",
    },
    {
        "index": 1,
        "id": 2,
        "name": "The Power of Now",
        "price": 650,
        "description": "This book is a spiritual guide to living in the present moment. Tolle argues that most human suffering is caused by our attachment to the past or the future, and that we can find peace and happiness by focusing on the present moment. The book provides practical advice and exercises for achieving this state of mindfulness.",
    },
    {
        "index": 2,
        "id": 3,
        "name": "The 7 Habits of Highly Effective People",
        "price": 799,
        "description": "This self-help book is a classic in the genre, and has sold millions of copies worldwide. Covey presents seven habits that he believes are essential for personal and professional success, including taking initiative, setting goals, and communicating effectively.",
    },
    {
        "index": 3,
        "id": 4,
        "name": "The Immortal Life of Henrietta Lacks",
        "price": 1099,
        "description": "This book tells the story of Henrietta Lacks, a woman whose cancer cells were used without her knowledge or consent to develop the first immortal human cell line. Skloot explores the ethical and scientific implications of this case, as well as the impact it had on Lacks' family.",
    },
]


def index(request):
    return render(request, "main/base_layout.html")


def _get_books(book_id):
    for book in My_Books:
        if "id" in book and book["id"] == book_id:
            return book
    return None


def books_list(request):
    my_context = {"books_list": My_Books}
    return render(request, "books/books_list.html", context=my_context)


def book_details(request, **kwargs):
    book_id = kwargs.get("book_id")
    book_object = _get_books(book_id)
    my_context = {
        "book_id": book_object.get("id"),
        "book_name": book_object.get("name"),
        "book_price": book_object.get("price"),
        "book_description": book_object.get("description"),
    }
    return render(request, "books/book_details.html", context=my_context)

def book_delete(request, **kwargs):
    book_id = kwargs.get('book_id')
    book_object = _get_books(book_id)
    if book_object:
        My_Books.remove(book_object)
    return redirect('books:books_list')

def book_update(request, **kwargs):
    book_id = kwargs.get('book_id')
    book_object = _get_books(book_id)
    for book in My_Books:
        if book == book_object:
            book['name'] = f"Update {book_object['name']}"
    return redirect('books:books_list')

def book_add(request):
    new_index = max(book['index'] for book in My_Books) + 1
    new_book = {
        'index': new_index,
        'id': new_index + 1,
        'name':"New Book",
        'price': 750,
        'description': "Book description",
    }
    My_Books.append(new_book)
    return redirect('books:books_list')

Lab1/BookStore/templates/books/book_details.html
{% extends 'main/base_layout.html' %}


{% block main-content %}
<div class="container-fluid d-flex flex-column justify-content-center align-items-center" style="height: 80vh;">
  <h2 class="text-center fw-light"> Welcome to Book Details </h2>
  <div class="d-flex justify-content-center mt-3 p-2 ">
    <div class="card col-4 d-flex flex-column align-items-center">
        <div class="card-body d-flex flex-column align-items-center">
          <h5 class="card-title">Book Name: <span class="text-secondary">{{ book_name }}</span></h5>
          <h6 class="card-subtitle mb-2 text-muted">Book ID: {{ book_id }}</h6>
          <p class="card-text fw-light">{{ book_description }}</p>
        </div>
        <span class="my-3" {% if book_price > 1000 %} style="color:red" {% else %} style="color:green" {% endif %}>Price: {{ book_price }} EGP</li></span>
    </div>
  </div>
</div>
{% endblock %}

Lab1/BookStore/templates/books/books_list.html
{% extends 'main/base_layout.html' %}

{# override block title #}
{% block title %}
    Books List
{% endblock %}

{# override body #}
{% block main-content %}
<div class="container" style="height: 90vh;">
    <div class="d-flex text-center my-4 justify-content-end ">
        <a class="btn btn-success" href="{% url 'books:book_add' %}">Add New Book</a>
    </div>

    <table class="container table table-condensed text-center">
    <thead>
        <tr>
            <th> ID </th>
            <th> Name </th>
            <th> Price </th>
            <th> Description </th>
            <th> Actions </th>
        </tr>
    </thead>
    
    <tbody>
        {% for book in books_list %}
        <tr {% if book.price > 1000 %} style="color:red" {% else %} style="color:green" {% endif %} >
        <td> {{ book.id }} </td>
        <td> {{ book.name }} </td>
        <td> {{ book.price }} EGP</td>
        <td> {{ book.description | truncatewords:2  | title }} </td>
        
        <td> 
            <a class="btn btn-primary text-light" href="{% url 'books:book_details' book.id %}"> View</a>
            <a class="btn btn-info text-light" href="{% url 'books:book_update' book.id %}"> Update</a>
            <a class="btn btn-danger text-light" href="{% url 'books:book_delete' book.id %}"> Delete</a> 
        </td>
    </tr>

    {% empty %}
    <tr>
        <td colspan="5" class="text-center"> Sorry, This Book Not Found in The List</td>
    </tr>
    {% endfor %}
    </tbody>

    </table>
</div>
{% endblock %}